version: '3.3'

services:
  sdc-nginx:
    build:
      context: docker
    container_name: sdc-nginx-ssl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 443:443
    networks:
      - app_network

networks:
  app_network:
