version: '3.3'

services:
  sdc-nginx:
    image: butch/sdc-nginx:1.0.0
    container_name: sdc-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    ports:
      - 80:80
    networks:
      - app_network

networks:
  app_network:
